### ISSUE TITLE
cannot generate pdf as root.

### ISSUE THREAD

**Issue by danner** [KohheePeace/docusaurus-pdf#1]
I'm using containers, and when I try to run docusaurus-pdf as part of the build, I get this error.
```
+ npm run generate-pdf

> <myapp>@0.0.0 generate-pdf /tmp/build/a45049ad/dev-code
> docusaurus-pdf http://localhost:3000/index myPDF.pdf && mv myPDF.pdf static/myPDF.pdf

Error: Failed to launch the browser process!
[0401/201553.412728:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/tmp/build/a45049ad/dev-code/node_modules/puppeteer/lib/Launcher.js:750:14)
    at Interface.<anonymous> (/tmp/build/a45049ad/dev-code/node_modules/puppeteer/lib/Launcher.js:739:50)
    at Interface.emit (events.js:214:15)
    at Interface.close (readline.js:403:8)
    at Socket.onend (readline.js:180:10)
    at Socket.emit (events.js:214:15)
    at endReadableNT (_stream_readable.js:1178:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! <myapp>@0.0.0 generate-pdf: `docusaurus-pdf http://localhost:3000/index myPDF.pdf && mv myPDF.pdf static/myPDF.pdf`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the <myapp>@0.0.0 generate-pdf script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I know this is alpha, I know it's still very fresh, so I just wanted to let you know about this.

I tried a couple of the things mentioned here: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md#recommended-enable-user-namespace-cloning but none of them worked in a way that didn't seem incredibly disruptive from the normal pattern.

I also tried to modify the ENV variables
```
export PUPPETEER_EXECUTABLE_PATH="$ROOT_FOLDER/dev-code/$(ls node_modules/puppeteer/.local-chromium/linux-*/chrome-linux/chrome_sandbox) --no-sandbox"
```
but that says it cannot locate an executable at that path.

Workaround that finally worked:
Creating a wrapper around the official chrome that was installed on the container, and adding no sandbox to it. 
```
echo 'exec /opt/google/chrome/chrome --no-sandbox "$@"' > chrome-wrapper
chmod 755 chrome-wrapper
export PUPPETEER_EXECUTABLE_PATH="$(pwd)/chrome-wrapper"
npm run generate-pdf
```

**Comment by KohheePeace** [comment]
sorry for wasting your time.

This plugin is not intended to use during build time and with container.🙇

**Comment by KohheePeace** [comment]
I will add note in Readme.

**Comment by danner** [comment]
I'm closing this based on the README stating this usage is not intended, but I still want to keep the solution around for others to see.
