### ISSUE TITLE
Error when building pdf with baseUrl parameter

### ISSUE THREAD

**Issue by fasolens** [KohheePeace/docusaurus-pdf#11]
I have set `baseUrl: '/docs/'` and run the **docusaurus-pdf** with:
`npx docusaurus-pdf from-build build/ docs/Wiki/Main_Page /docs/ --output-file build/img/docusaurus.pdf`

When I change baseUrl to `'/'` and build documentation and then build pdf without baseurl parameter, it works fine.

```
Error: Loading style from http://127.0.0.1:32831/docs/styles.da06b8e4.css failed
    at DOMWorld.addStyleTag (/home/fasolens/docs/node_modules/puppeteer/lib/DOMWorld.js:307:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
  -- ASYNC --
    at Frame.<anonymous> (/home/fasolens/docs/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.addStyleTag (/home/fasolens/docs/node_modules/puppeteer/lib/Page.js:429:29)
    at Page.<anonymous> (/home/fasolens/docs/node_modules/puppeteer/lib/helper.js:112:23)
    at /home/fasolens/docs/node_modules/docusaurus-pdf/lib/index.js:161:47
    at step (/home/fasolens/docs/node_modules/docusaurus-pdf/lib/index.js:33:23)
    at Object.next (/home/fasolens/docs/node_modules/docusaurus-pdf/lib/index.js:14:53)
    at fulfilled (/home/fasolens/docs/node_modules/docusaurus-pdf/lib/index.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by fasolens** [comment]
I have found the solution. The problem is with baseUrl argument. When I write pure `docs` without slashes it works.

`npx docusaurus-pdf from-build build/ docs/Wiki/Main_Page docs --output-file build/img/docusaurus.pdf`
