### ISSUE TITLE
generate  PDF   fail

### ISSUE THREAD

**Issue by ywjr** [kohheepeace/docusaurus-pdf#29]
npx docusaurus-pdf   http://localhost:3000/platformintro/intro    intro.pdf

Error: The src attribute of the 'styles*.js' file could not be found!
    at getScriptPathFromHTML (C:\Users\lenovo\AppData\Roaming\npm-cache\_npx\5804\node_modules\docusaurus-pdf\lib\index.js:100:15)
    at C:\Users\lenovo\AppData\Roaming\npm-cache\_npx\5804\node_modules\docusaurus-pdf\lib\index.js:164:42
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by antonygibbs** [comment]
Probably needs updating for Docusaurus 2.0.0-beta0?

**Comment by ywjr** [comment]
Sorry, I can't link to GitHub now. I can't reply&nbsp; you directly&nbsp;&nbsp;


Sorry, I can't link to GitHub now. I can't answer you directly


I have tested 2.0.0-beta.0 and 2.0.0-alpha.73, and the test results are as follows


1. PDF file can be generated on 2.0.0-alpha.73,


2。 However, it failed to run on 2.0.0-beta.0. It can't generate PDF. The failure information is like the above post.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kohheepeace/docusaurus-pdf"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月18日(星期二) 晚上9:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kohheepeace/docusaurus-pdf] generate  PDF   fail (#29)





 
Probably needs updating for Docusaurus 2.0.0-beta0?

**Comment by ywjr** [comment]
Sorry, I can only reply by mail now。


I suggest another function:


Multiple MD files are merged and generated into a PDF file





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kohheepeace/docusaurus-pdf"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月18日(星期二) 晚上9:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kohheepeace/docusaurus-pdf] generate  PDF   fail (#29)





 
Probably needs updating for Docusaurus 2.0.0-beta0?

**Comment by ywjr** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kohheepeace/docusaurus-pdf"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月18日(星期二) 晚上9:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kohheepeace/docusaurus-pdf] generate  PDF   fail (#29)





 
Probably needs updating for Docusaurus 2.0.0-beta0?

**Comment by covalentbond** [comment]
I've been facing the same issue - is there any soultion to it?

**Comment by kohheepeace** [comment]
@covalentbond, @ywjr Are you using docusaurus v1?　[This npm](https://github.com/kohheepeace/mr-pdf) will create a PDF file for v1.

@antonygibbs Thanks 👍

**Comment by covalentbond** [comment]
Thanks @kohheepeace - But I've been using the latest version `2.0.0-beta.0` only

**Comment by kohheepeace** [comment]
I've noticed @ywjr have written it already. Too hard to read.

@covalentbond I've confirmed that https://github.com/kohheepeace/mr-pdf works correctly for v2 beta. Could you also check if it works ? I will merge the code of mr-pdf to docusaurus-pdf.

**Comment by kohheepeace** [comment]
@covalentbond And `docusaurus-pdf` cannot generate PDF for homepage. https://zowe-docs.netlify.app/ is homepage not docs page.

**Comment by ywjr** [comment]
&nbsp;
&nbsp; the test results are as follows


1. PDF file can be generated on v2.0.0-alpha.73,


2。 However, it failed to run on v2.0.0-beta.0. It can't generate PDF.&nbsp;


The failure information is like the above post.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kohheepeace/docusaurus-pdf"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月19日(星期三) 下午5:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kohheepeace/docusaurus-pdf] generate  PDF   fail (#29)





 
@covalentbond, @ywjr Are you using docusaurus v1?　This npm will create a PDF file for v1.
 
@antonygibbs Thanks 👍

**Comment by kohheepeace** [comment]
@ywjr Hey, please write the issue proper as possible as you can. It distracts me from reading and dealing with issues. 😠

**Comment by covalentbond** [comment]
@kohheepeace [mr-pdf](https://github.com/kohheepeace/mr-pdf) worked for `2.0.0.beta-0` site. Thank you! 🙌

My concern is I've swizzled the `DocItem` component as you may find [here](https://zowe-docs.netlify.app/stable/getting-started/overview). While generating the PDF these components are also being printed:

1. ![image](https://user-images.githubusercontent.com/53327173/118799497-6a32ab00-b8bc-11eb-839d-a0475ef0285a.png)
2. ![image](https://user-images.githubusercontent.com/53327173/118799602-8898a680-b8bc-11eb-986c-83e92d527374.png)

Is there any way - we can prevent it

**Comment by kohheepeace** [comment]
@covalentbond yes!😀 You can exclude unnecessary HTML elements by using `--excludeSelectors`

```
npx mr-pdf ... --excludeSelectors=".docsRating"
````

Is this working ?

**Comment by covalentbond** [comment]
@kohheepeace no it doesn't seem to work. Not sure if I'm doing it right.

The first swizzled component shown has `.docsRating` class attached to it. Similarly the second one has a `.navbar__inner` class.

As mentioned in **CLI Options**, attached the selectors in the similar way - but doesn't seem to work. Attached the two classes without space at the last:
```
npx mr-pdf --initialDocsURL="https://zowe-docs.netlify.app/stable/getting-started/overview" --paginationSelector=".pagination-nav__item--nxt > a" --excludeSelectors=".announcementBar_UUUQ,nav.navbar,.docSidebarContainer_3pwe,.docMainContainer_2pgU .col.col--3,footer.footer,.doctemContainer_2szM > .margin-vert--xl > .row > .col:first-child,.pagination-nav,.docsRating,navbar__inner"
```

**Comment by covalentbond** [comment]
@kohheepeace thanks it worked! 🎉

**Comment by antonygibbs** [comment]
@kohheepeace Thanks so much for pointing out [mr-pdf](https://github.com/kohheepeace/mr-pdf). I was able to get great PDF documentation from the command line ```npx mr-pdf --initialDocsURL="http://localhost:3000/docs/{starting-page}" --paginationSelector=".pagination-nav__item--next > a"```, but found that this included the 'Edit this page' icon and link. I was unable to determine how to exclude this in the parameter ```--excludeSelectors```. Are you able to help on that detail? (I found that all other exclusions I needed happened by default 😃)

**Comment by kohheepeace** [comment]
@antonygibbs 
You can use chrome devtools to detect the CSS class for 'Edit this page' icon and link.

**But... there is no specific Class** for this element...
![image](https://user-images.githubusercontent.com/29557494/118827566-7556fc80-b8f7-11eb-9da9-d4245ab6cc8a.png)


Is this one working ?
```
--excludeSelectors=".margin-vert--xl a"
```



> (I found that all other exclusions I needed happened by default 😃)

=> Yes, I've also noticed this. Maybe docusaurus added CSS for print PDF by default.

**Comment by antonygibbs** [comment]
@kohheepeace That totally worked! Thank you so much for responding to this thread today to offer assistance to us all, and the alternative of mr-pdf is great for some other teams here too, I am spreading the word!

**Comment by ACavdar** [comment]
> ... . I was able to get great PDF documentation from the command line `npx mr-pdf --initialDocsURL="http://localhost:3000/docs/{starting-page}" --paginationSelector=".pagination-nav__item--next > a"`, but .... 

@antonygibbs How can this command work? The command you passed above has parameter `--initialDocsURL`, but documentation of mr-pdf gives; `--initialDocURLs` (note the location of letter s) . I am really confused, help me out here. @kohheepeace @antonygibbs . The command works with parameter described in the documentation;  `--initialDocURLs` .

I use Docusaurus 2.1.0 (tried with 2.0 beta versions first) and need to generate PDF from the documentation but, below is my adventure with no luck. 

```
npx mr-pdf --initialDocsURL="http://localhost:3000/docs/intro" --paginationSelector=".pagination-nav__item--next > a" --excludeSelectors=".margin-vert--xl a"

error: unknown option '--initialDocsURL'

------------------------------

npx mr-pdf --initialDocURLs="http://localhost:3000/docs/intro" --paginationSelector=".pagination-nav__item--next > a" --excludeSelectors=".margin-vert--xl a"

error: required option '--contentSelector <selector>' not specified

-------------------------------

npx mr-pdf --initialDocURLs="http://localhost:3000/docs/intro" --paginationSelector=".pagination-nav__item--next > a" --excludeSelectors=".margin-vert--xl a" --contentSelector="article"

-- result: PDF generated. Only first page (intro) 
```

The CSS selector for next page link has also changed in 2.0 versions. It was `.pagination-nav__item--next` but now it is `.pagination-nav__link--next` . 

I would appreciate your help to generate PDF with all pages in my Docusaurus documentation project.

**Comment by ACavdar** [comment]
@idontknowjs  : 

> Thanks @kohheepeace - But I've been using the latest version `2.0.0-beta.0` only.
> 
> ![image](https://user-images.githubusercontent.com/53327173/118795665-74eb4100-b8b8-11eb-8edf-008df5bb991a.png)

I, too get the same error, and also with `href` instead of `src` sometimes. Did you manage to find a solution for that? 
I used Docusaurus versions `2.0.0-beta.14` and `2.1.0`.

**Comment by RiNaPa** [comment]
Is there any way I can generate pdf of site on button click instead of command line?
