### ISSUE TITLE
Issue installing when using Mojave system 

### ISSUE THREAD

**Issue by jonsanjuan** [KohheePeace/docusaurus-pdf#6]
Hi Kohhee. I had better luck installing on a Mojave system.  Now when i try to execute the Generating PDF I get the following error 

This was using the tutorial docusaurus site: 

Generating PDF of https://docusaurus.io/docs/en/tutorial-setup

Error: Loading style from https://docusaurus.io//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/atom-one-dark.min.css failed
    at DOMWorld.addStyleTag (/Users/j/.npm/_npx/15518/lib/node_modules/docusaurus-pdf/node_modules/puppeteer/lib/DOMWorld.js:307:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
  -- ASYNC --
    at Frame.<anonymous> (/Users/j/.npm/_npx/15518/lib/node_modules/docusaurus-pdf/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.addStyleTag (/Users/j/.npm/_npx/15518/lib/node_modules/docusaurus-pdf/node_modules/puppeteer/lib/Page.js:429:29)
    at Page.<anonymous> (/Users/j/.npm/_npx/15518/lib/node_modules/docusaurus-pdf/node_modules/puppeteer/lib/helper.js:112:23)
    at /Users/j/.npm/_npx/15518/lib/node_modules/docusaurus-pdf/lib/index.js:161:47
    at step (/Users/j/.npm/_npx/15518/lib/node_modules/docusaurus-pdf/lib/index.js:33:23)
    at Object.next (/Users/j/.npm/_npx/15518/lib/node_modules/docusaurus-pdf/lib/index.js:14:53)
    at fulfilled (/Users/j/.npm/_npx/15518/lib/node_modules/docusaurus-pdf/lib/index.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
js-MacBook-Pro:website j$ 

and this was the error when I tried do a local test from mylaptop

Generating PDF of https://docusaurus.io/docs/en/tutorial-setup

Error: Loading style from https://docusaurus.io//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/atom-one-dark.min.css failed
    at DOMWorld.addStyleTag (/Users/j/.npm/_npx/15518/lib/node_modules/docusaurus-pdf/node_modules/puppeteer/lib/DOMWorld.js:307:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
  -- ASYNC --
    at Frame.<anonymous> (/Users/j/.npm/_npx/15518/lib/node_modules/docusaurus-pdf/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.addStyleTag (/Users/j/.npm/_npx/15518/lib/node_modules/docusaurus-pdf/node_modules/puppeteer/lib/Page.js:429:29)
    at Page.<anonymous> (/Users/j/.npm/_npx/15518/lib/node_modules/docusaurus-pdf/node_modules/puppeteer/lib/helper.js:112:23)
    at /Users/j/.npm/_npx/15518/lib/node_modules/docusaurus-pdf/lib/index.js:161:47
    at step (/Users/j/.npm/_npx/15518/lib/node_modules/docusaurus-pdf/lib/index.js:33:23)
    at Object.next (/Users/j/.npm/_npx/15518/lib/node_modules/docusaurus-pdf/lib/index.js:14:53)
    at fulfilled (/Users/j/.npm/_npx/15518/lib/node_modules/docusaurus-pdf/lib/index.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
js-MacBook-Pro:website j$ 

Thanks in advanced

**Comment by KohheePeace** [comment]
Oh, this plugin only support v2 of docusaurus. I completely missed adding this note in README. Really sorry for troubling you.

**Comment by jonsanjuan** [comment]
That explains it.  Is there an alternative converter you recommend for Docusaurus 1.x?

**Comment by KohheePeace** [comment]
Sorry I dont know 😢 Maybe the fastest way is upgrading your website version to v2.
